import { useState, useEffect } from 'react'
import Head from 'next/head'
import { FaExternalLinkAlt, FaSearch } from 'react-icons/fa'

import styles from 'shared/styles/Home.module.css'
import BoardModel from 'shared/models/Board'
import { IBoard } from 'shared/interfaces/board'
import { Matrix } from 'shared/components/organisms'

const API_URL = 'http://localhost:3000/api'

export default function Home() {
  const [board, setBoard] = useState<BoardModel>()

  function fetchBoard() {
    (async () => {
      const boardResponse: IBoard =
        await fetch(`${API_URL}/trello/board`).then(response => response.json())

      setBoard(new BoardModel(boardResponse))
    })()
  }

  useEffect(fetchBoard, [])

  if (!board)
    return (
      <div className={styles.main}>
        <FaSearch size={25} className={styles.loading} />
      </div>
    )

  return (
    <div className={styles.container}>
      <Head>
        <title>{board.getName()}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {`${board.getName()} `}
          <a href={board.getUrl()} target="_blank" rel="noopener noreferrer">
            <FaExternalLinkAlt size={15} />
          </a>
        </h1>

        <Matrix lists={board.getList()} />
      </main>
    </div>
  )
}
